quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/reservas

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.http.port=8082
auth.issuer=vehiculo-auth
auth.token.ttl=3600
smallrye.jwt.sign.key.location=privateKey.pem

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*

#esto es para el api
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/reservas
quarkus.hibernate-orm.database.generation=update
# quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
#el path raíz de la aplicación, para que todas las rutas de los recursos estén bajo /aerolinea/api/v1.0, por ejemplo, el recurso de usuarios estaría en /aerolinea/api/v1.0/usuarios
quarkus.http.root-path=/vehiculo/api/v1.0
quarkus.http.port=8081
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
# validar token
# la ubicación de la clave pública para verificar los tokens JWT, debe estar en el classpath, en este caso se llama publicKey.pem y debe estar en src/main/resources
mp.jwt.verify.publickey.location=publicKey.pem
# lo uso en el authorization server
# el issuer del token, debe ser el mismo que se usó para firmar el token en el authorization server, en este caso es vuelo-auth
mp.jwt.verify.issuer=vehiculo-auth
# Activar seguridad
quarkus.smallrye-jwt.enabled=false